name: CI

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - "**.md"

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Verify with Maven
        run: ./mvnw -B --update-snapshots verify

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container image
        uses: docker/build-push-action@v7
        env:
          DOCKER_BUILD_RECORD_UPLOAD: "false"
          DOCKER_BUILD_SUMMARY: "false"
        with:
          context: .
          file: ./Containerfile
          push: false
          tags: docker.io/alecigne/somafm-song-history:ci
