# Workflow run on release.
# 1. Run unit tests.
# 2. Run integration tests.
# 3. Package.
# 4. Build image.
# 5. Run smoke tests on container.
# 6. Publish image on Dockerhub.
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  pipeline:
    uses: ./.github/workflows/_pipeline.yml
    with:
      run-smoke: true
      publish-image: true
    secrets: inherit
