name: Smoke

on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - "**.md"

jobs:
  pipeline:
    uses: ./.github/workflows/_pipeline.yml
    with:
      run-smoke: true
      publish-image: false
